-- Generated by mywm from a wallpaper.
return {
  base00 = '{{ colors.surface.default.hex }}',
  base01 = '{{ colors.surface_container_low.default.hex }}',
  base02 = '{{ colors.surface_container_high.default.hex }}',
  base03 = '{{ colors.on_surface_variant.default.hex }}',
  base04 = '{{ colors.outline.default.hex }}',
  base05 = '{{ colors.on_surface.default.hex }}',
  base06 = '{{ colors.on_surface.default.hex }}',
  base07 = '{{ colors.surface_bright.default.hex }}',
  base08 = '{{ colors.terminal_normal_red.default.hex }}',
  base09 = '{{ colors.terminal_normal_magenta.default.hex }}',
  base0A = '{{ colors.terminal_normal_yellow.default.hex }}',
  base0B = '{{ colors.terminal_normal_green.default.hex }}',
  base0C = '{{ colors.terminal_normal_cyan.default.hex }}',
  base0D = '{{ colors.terminal_normal_blue.default.hex }}',
  base0E = '{{ colors.terminal_bright_magenta.default.hex }}',
  base0F = '{{ colors.tertiary.default.hex }}',
}
